[debug] [2023-10-28T12:23:09.010Z] ----------------------------------------------------------------------
[debug] [2023-10-28T12:23:09.016Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2023-10-28T12:23:09.018Z] CLI Version:   12.7.0
[debug] [2023-10-28T12:23:09.019Z] Platform:      win32
[debug] [2023-10-28T12:23:09.019Z] Node Version:  v18.14.0
[debug] [2023-10-28T12:23:09.021Z] Time:          Sat Oct 28 2023 17:53:09 GMT+0530 (India Standard Time)
[debug] [2023-10-28T12:23:09.021Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-10-28T12:23:09.025Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-10-28T12:23:09.169Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-10-28T12:23:09.169Z] > authorizing via signed-in user (p.anant223@gmail.com)
[debug] [2023-10-28T12:23:09.170Z] [iam] checking project netflixgpt-3a69b for permissions ["firebase.projects.get"]
[debug] [2023-10-28T12:23:09.170Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:23:09.171Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:23:09.171Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:23:20.257Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: getaddrinfo ENOTFOUND firebase-public.firebaseio.com
[warn] !  Unable to fetch the CLI MOTD and remote config. 
[debug] [2023-10-28T12:23:20.260Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2023-10-28T12:23:24.291Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------527687608873365063633211","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-10-28T12:23:24.292Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:23:24.293Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:23:24.293Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:23:24.293Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:23:35.498Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------320435595366012576746496","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-10-28T12:23:35.500Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:23:35.519Z] FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
    at invalidCredentialError (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\auth.js:144:12)
    at refreshTokens (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\auth.js:508:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.getAccessToken (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:149:22)
    at async Client.addAuthHeader (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:140:21)
    at async Client.request (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:96:34)
    at async getFirebaseProject (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\management\projects.js:295:21)
    at async needProjectNumber (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\projectUtils.js:46:22)
    at async C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\command.js:226:17
[error] 
[error] Error: Failed to get Firebase project netflixgpt-3a69b. Please make sure the project exists and your account has permission to access it.
[debug] [2023-10-28T12:27:27.477Z] ----------------------------------------------------------------------
[debug] [2023-10-28T12:27:27.480Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2023-10-28T12:27:27.481Z] CLI Version:   12.7.0
[debug] [2023-10-28T12:27:27.481Z] Platform:      win32
[debug] [2023-10-28T12:27:27.482Z] Node Version:  v18.14.0
[debug] [2023-10-28T12:27:27.482Z] Time:          Sat Oct 28 2023 17:57:27 GMT+0530 (India Standard Time)
[debug] [2023-10-28T12:27:27.482Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-10-28T12:27:27.485Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-10-28T12:27:27.709Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-10-28T12:27:27.710Z] > authorizing via signed-in user (p.anant223@gmail.com)
[debug] [2023-10-28T12:27:27.710Z] [iam] checking project netflixgpt-3a69b for permissions ["firebase.projects.get"]
[debug] [2023-10-28T12:27:27.711Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:27:27.711Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:27:27.712Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:27:29.202Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2023-10-28T12:27:29.203Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2023-10-28T12:27:49.246Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------687032704317755113716631","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 142.250.194.170:443
[debug] [2023-10-28T12:27:49.247Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:27:49.248Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:27:49.249Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:27:49.249Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:28:10.310Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------126128453417369909498661","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 142.250.194.170:443
[debug] [2023-10-28T12:28:10.310Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:28:15.328Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:254:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2023-10-28T12:28:34.913Z] ----------------------------------------------------------------------
[debug] [2023-10-28T12:28:34.916Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2023-10-28T12:28:34.916Z] CLI Version:   12.7.0
[debug] [2023-10-28T12:28:34.917Z] Platform:      win32
[debug] [2023-10-28T12:28:34.917Z] Node Version:  v18.14.0
[debug] [2023-10-28T12:28:34.918Z] Time:          Sat Oct 28 2023 17:58:34 GMT+0530 (India Standard Time)
[debug] [2023-10-28T12:28:34.918Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-10-28T12:28:35.124Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-10-28T12:28:35.125Z] > authorizing via signed-in user (p.anant223@gmail.com)
[debug] [2023-10-28T12:28:35.125Z] [iam] checking project netflixgpt-3a69b for permissions ["firebase.projects.get"]
[debug] [2023-10-28T12:28:35.126Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:28:35.128Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:28:35.128Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:28:56.179Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------407746666625516832578045","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 142.250.194.170:443
[debug] [2023-10-28T12:28:56.181Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:28:56.182Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:28:56.183Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:28:56.183Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:29:17.228Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------129184570220460432942122","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 142.250.194.170:443
[debug] [2023-10-28T12:29:17.229Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:29:22.245Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:254:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2023-10-28T12:30:30.726Z] ----------------------------------------------------------------------
[debug] [2023-10-28T12:30:30.727Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2023-10-28T12:30:30.728Z] CLI Version:   12.7.0
[debug] [2023-10-28T12:30:30.728Z] Platform:      win32
[debug] [2023-10-28T12:30:30.728Z] Node Version:  v18.14.0
[debug] [2023-10-28T12:30:30.729Z] Time:          Sat Oct 28 2023 18:00:30 GMT+0530 (India Standard Time)
[debug] [2023-10-28T12:30:30.729Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-10-28T12:30:30.894Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-10-28T12:30:30.895Z] > authorizing via signed-in user (p.anant223@gmail.com)
[debug] [2023-10-28T12:30:30.895Z] [iam] checking project netflixgpt-3a69b for permissions ["firebase.projects.get"]
[debug] [2023-10-28T12:30:30.896Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:30:30.900Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:30:30.900Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:30:42.104Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------282055713788721407396813","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-10-28T12:30:42.106Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:30:42.107Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:30:42.107Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:30:42.108Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:31:17.655Z] ----------------------------------------------------------------------
[debug] [2023-10-28T12:31:17.657Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2023-10-28T12:31:17.657Z] CLI Version:   12.7.0
[debug] [2023-10-28T12:31:17.657Z] Platform:      win32
[debug] [2023-10-28T12:31:17.658Z] Node Version:  v18.14.0
[debug] [2023-10-28T12:31:17.658Z] Time:          Sat Oct 28 2023 18:01:17 GMT+0530 (India Standard Time)
[debug] [2023-10-28T12:31:17.658Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-10-28T12:31:17.808Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-10-28T12:31:17.808Z] > authorizing via signed-in user (p.anant223@gmail.com)
[debug] [2023-10-28T12:31:17.809Z] [iam] checking project netflixgpt-3a69b for permissions ["firebase.projects.get"]
[debug] [2023-10-28T12:31:17.810Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:31:17.811Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:31:17.811Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:31:29.019Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------396335279285503003517971","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-10-28T12:31:29.021Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:31:29.022Z] > refreshing access token with scopes: []
[debug] [2023-10-28T12:31:29.023Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-28T12:31:29.023Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-28T12:31:40.211Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------684559968674667558590166","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-10-28T12:31:40.212Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-28T12:31:45.234Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\Anant\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:254:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
